Apply `black`, `isort` and `ruff` to the whole code
bomzheg/KarmaBot pull request #167
Opened 2024-02-13 15:04 UTC by Desiders

Close #126

2024-02-20 10:54 UTC, Lamroy95 approved these changes

2024-02-20 11:31 UTC, bomzheg requested changes

2024-02-20 11:31 UTC, bomzheg commented on app/handlers/base.py
> +    text = f"id этого чата: {hpre(message.chat.id)}\n" f"Ваш id: {hpre(message.from_user.id)}"
it's ugly, please two string literals (remove " f" from middle)

2024-02-20 11:31 UTC, bomzheg commented on .pre-commit-config.yaml
> -      - id: black
plese add here `ruff --format .`

2024-02-20 11:31 UTC, bomzheg commented on .github/workflows/lint.yml
> -        black --config=pyproject.toml --check --diff --verbose ${{ steps.changed-python-files.outputs.all_changed_files }}
please restore it with something like `ruff format --check .`

2024-02-20 11:53 UTC, Desiders commented
I think we also need to add `ruff check` in pipeline before `ruff format`

2024-02-20 12:03 UTC, Lamroy95 requested changes

2024-02-20 12:03 UTC, Lamroy95 commented on .github/workflows/lint.yml
You can remove Get changed files step since the whole project is formatted

2024-02-20 12:03 UTC, Lamroy95 commented on .github/workflows/lint.yml
> +        ruff format --check --config=pyproject.toml ${{ steps.changed-python-files.outputs.all_changed_files }}
Since the whole project is formatted
```suggestion
        ruff format --check --config=pyproject.toml .
```

2024-02-20 13:21 UTC, Lamroy95 approved these changes

2024-02-20 18:37 UTC, bomzheg requested changes

2024-02-20 18:37 UTC, bomzheg commented on .github/workflows/lint.yml
> +        ruff format --check --config=pyproject.toml .
we still needed `ruff check .` in our pipeline. it not hte same with `ruff format --check`

2024-02-21 09:19 UTC, bomzheg approved these changes

2024-02-21 09:19 UTC, merged